SET NOCOUNT ON

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'DBO.X'))
    DROP TABLE X

DECLARE @c INT, @flag CHAR = 'r'

SET IMPLICIT_TRANSACTIONS ON

CREATE TABLE X (K INT)
INSERT X VALUES (1),(2),(3)

SET @c = (SELECT COUNT(*) FROM X)
PRINT 'Количество строк в таблице X: ' + CAST(@c AS VARCHAR(2))

IF @flag = 'r'
    COMMIT
ELSE
    ROLLBACK

SET IMPLICIT_TRANSACTIONS OFF

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'DBO.X'))
    PRINT 'Таблица X есть'
ELSE
    PRINT 'Таблицы X нет'

----

SET NOCOUNT ON

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'DBO.Y'))
    DROP TABLE Y

DECLARE @c INT, @flag CHAR = 'r'

SET IMPLICIT_TRANSACTIONS ON

CREATE TABLE Y (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(50),
    Age INT
)

INSERT Y (Name, Age) VALUES
    ('John', 30),
    ('Jane', 25),
    ('Bob', 35)

SET @c = (SELECT COUNT(*) FROM Y)
PRINT 'Количество строк в таблице Y: ' + CAST(@c AS VARCHAR(2))

IF @flag = 'c'
    COMMIT
ELSE
    ROLLBACK

SET IMPLICIT_TRANSACTIONS OFF

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'DBO.Y'))
    PRINT 'Таблица Y есть'
ELSE
    PRINT 'Таблицы Y нет'
